---
quiz:
  cosmetic:
    color:
      orange: "#FFA500"
      red: "#E50000"
      green: "#32cd32"
    emoji:
      correct: ":white_check_mark:"
      incorrect: ":x:"
    button_styles:
      default: "default"
      green: "primary"
      red: "danger"
  text:
    play_again: "Would you like to play again?"
    leaderboard:
      header: "*Pokemon Masters*"
      no_answered_questions: |
        Sorry doesn't look like your team has answered any questions. Say @pokequiz let's start a quiz to get answering
        some questions!
  values:
    leaderboard:
      max_users: 10
    answer_values:
      correct: 1
      incorrect: -1
messaging:
  intro_message: |
    Okay trainer, let's catch them all! :smiley:
  unknown_command: |
    Sorry ${user_id} I didn't quite get that. If you want to start a quiz say
    something with quiz in it :grin: e.g. @pokequiz let's start a quiz! Also mention me with the word help
    to view some instructions.
  help_command: |
    Hey ${user_id} :grin: you can mention me along with the word *quiz* to start a quiz e.g. @pokequiz let's start
    a quiz! You can mention me along with the word *leaderboard* to view your teams leaderboard e.g. @pokequiz
    show me the leaderbaord! You can mention me along with the word *help* to view this message e.g. @pokequiz help me!
    For more information you can view the guide here https://pokequiz.xyz/guide
  correct:
    streak:
      greater_ten: |
        Nice one ${user_id} that's your ${streak}th correct answer in a row! :astonished:
      greater_hundred: |
        :tada: :tada: :tada: WOW ${user_id} that's your ${streak}th correct answer in a row!
        :tada: :tada: Congratulations you truly are a Pokemon master! :tada:
      no_streak: |
        Nice one ${user_id} that's correct! :tada:
  incorrect:
    streak:
      greater_ten: |
        Sorry ${user_id} that's incorrect! :disappointed_relieved: You lost a ${streak} streak.
      no_streak: |
        Sorry ${user_id} that's incorrect! :disappointed_relieved:
oauth:
  redirect_success: "https://pokequiz.xyz/thanks"
events:
  trigger_words:
    quiz_start:
      - quiz
    leaderboard_show:
      - leaderboard
    help_show:
      - help