version: 1

formatters:
  simple:
    format: "[%(levelname)s] (%(name)s)  -  %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  __main__:
    level: DEBUG
    handlers: [console]
    propagate: yes